# Generated by Django 2.2.9 on 2020-01-07 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption')),
                ('status', models.CharField(choices=[('Posted', 'Posted'), ('Draft', 'Draft')], max_length=255, verbose_name='Status')),
                ('publishing_date', models.DateTimeField(blank=True, null=True, verbose_name='Publishing Date')),
                ('photo_file', models.ImageField(null=True, upload_to='images/', validators=[photos.models.validate_image_size], verbose_name='Photo File')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
